[dns]
# host = "0.0.0.0"
port = 2053

# [blocklists.abuse]
# url = "https://blocklistproject.github.io/Lists/alt-version/abuse-nl.txt"
# kind = "no-ip"

[blocklists.ads]
url = "https://blocklistproject.github.io/Lists/ads.txt"
kind = "etc-hosts"

# [blocklists.crypto]
# url = "https://blocklistproject.github.io/Lists/dnsmasq-version/crypto-dnsmasq.txt"
# kind = "dnsmasq"

# [blocklists.drugs]
# url = "https://blocklistproject.github.io/Lists/adguard/drugs-ags.txt"
# kind = "adguard"

[database]
# url = "sqlite::memory:"

[lookup]
servers = ["1.1.1.1", "1.0.0.1"]
